### ISSUE TITLE
[Add] function that returns n-th term of the fibonacci sequence.

### ISSUE THREAD

**Issue by k3tanyadav** [imsuraj675/CodeStock#10]
I would like to add this function as per guidelines in [Contributions.md](https://github.com/imsuraj675/CodeStock/blob/main/Contribution.md) file.

- The function will solve the problem in O(n) time, given n is not too big (n<= 10^4 and about 100 test cases) to tackle time constraints.

**Comment by imsuraj675** [comment]
Have you filled the google form?

**Comment by k3tanyadav** [comment]
hi, where can I find the google form?

**Comment by servoserv** [comment]
hello  would like to work on this issue

**Comment by abhra2911** [comment]
I would like to work on this issue

**Comment by sayaksen18** [comment]
I am interested. Can i take it up?

**Comment by Soumyajit0803** [comment]
> I would like to add this function as per guidelines in [Contributions.md](https://github.com/imsuraj675/CodeStock/blob/main/Contribution.md) file.
> 
> * The function will solve the problem in O(n) time, given n is not too big (n<= 10^4 and about 100 test cases) to tackle time constraints.

Hi. Can you first tell us if you have registered under the [opensource event](https://winterofopensource.super.site/) or you want to collaborate outside of the event? Would be helpful for us. Thanks!

**Comment by imsuraj675** [comment]
@servoserv Go ahead. Add this function under Number theory. Make sure to write the most optimal code possible. (Mathematical formula)

**Comment by servoserv** [comment]
kindly check this pr
