### ISSUE TITLE
[ADD] Generate all substrings of a string (n^2)

### ISSUE THREAD

**Issue by ittou-shura** [imsuraj675/CodeStock#11]
implement function to generate all substrings of a a given string in O(n^2) TC

**Comment by ittou-shura** [comment]
i want to contribute to this as well.
Can i be assigned to this ?

**Comment by Vaibhavv1703** [comment]
Does it need to be generated in O(2^n) or O(n^2)? Also, I'm interested in contributing to this, and I'd like it assigned to me.

**Comment by imsuraj675** [comment]
@Vaibhavv1703 Go ahead. In this issue you have to return a list containing all strings (subsequences)

**Comment by Vaibhavv1703** [comment]
So, I have to implement a function that returns a list that contains all possible subsequences of a string. Is that right?

**Comment by imsuraj675** [comment]
Yes, but this is completed by ittou-shura. You can return a list that contains all substrings

**Comment by Vaibhavv1703** [comment]
All right, thank you for the clarification, I'll start working on it
