### ISSUE TITLE
[ADD] Array Functions: Count Occurrences of all Elements

### ISSUE THREAD

**Issue by Subhoshri** [imsuraj675/CodeStock#14]
To Add a function Count_Occurences which will count the number of times an element occurs in an array in Java, CPP and Python.

**Comment by imsuraj675** [comment]
@Subhoshri Go ahead. Make sure that you make generic functions. And return a dictionary, unordered_map, HashMap in respective languages.

**Comment by Subhoshri** [comment]
Thank you for assigning me this issue.

**Comment by Subhoshri** [comment]
> @Subhoshri Go ahead. Make sure that you make generic functions. And return a dictionary, unordered_map, HashMap in respective languages.

Okay, I will do that
