### ISSUE TITLE
[Add] String Algorithms: Generate all Substrings (2^n)

### ISSUE THREAD

**Issue by imsuraj675** [imsuraj675/CodeStock#2]
Add a function to generate all substrings (sub-sequences) in the structure as described in [Contribution.md](../blob/main/Contribution.md).
Give a small proposal describing your method of implementation.

Checklist:
- [ ] Added the files gen_substr.py, gen_substr.java and gen_substr.cpp in the corresponding directory
- [ ] My code aligns with the specified structure.
- [ ] Updated [RoadMap.md](../blob/main/RoadMap.md)

**Comment by ittou-shura** [comment]
I am interested in contributing to this issue.

**Comment by imsuraj675** [comment]
@ittou-shura Go ahead. Make the changes as specified.

**Comment by imsuraj675** [comment]
Have you filled the google form?

**Comment by ittou-shura** [comment]
Yes

**Comment by ittou-shura** [comment]
I filled just now 
I apologize for not having seen earlier.
Can i be reassigned to the issue?
