### ISSUE TITLE
[ADD] Number Theory Function: GCD using Euclidean Algorithm 

### ISSUE THREAD

**Issue by Subhoshri** [imsuraj675/CodeStock#22]
To find the GCD of 'a' and 'b' using Euclidean Algorithm. I want to work on this issue.

**Comment by imsuraj675** [comment]
@Subhoshri Go ahead. Make sure to write the most optimal code possible. And check that the code should give output for all the cases including, gcd(0,a), gcd(a,0) and gcd(0,0), where 'a' is any integer

**Comment by Subhoshri** [comment]
Okay, will do that.
