### ISSUE TITLE
Array Functions: Find Max-Min of an Array

### ISSUE THREAD

**Issue by Aditi-Anil-P** [imsuraj675/CodeStock#25]
To find the maximum and minimum element present in an array in

- Time Complexity - O(N)
- Space Complexity - O(1)
by implementing respective functions in  Java, C++ and Python.

**Comment by Aditi-Anil-P** [comment]
I would like to contribute to this issue

**Comment by imsuraj675** [comment]
@Aditi-Anil-P Go ahead. Don't use built-in functions. And make sure that your functions are generic, and instead of the element, return its index in the array. Make two functions, one for minimum and other for maximum

**Comment by mottawa** [comment]
Also me I would like to contribute to this issue

**Comment by imsuraj675** [comment]
> Also me I would like to contribute to this issue

Only one person can be assigned to one issue
