### ISSUE TITLE
[Add] Number Theory: Sieve of Eratosthenes (upto 'n' numbers)

### ISSUE THREAD

**Issue by imsuraj675** [imsuraj675/CodeStock#3]
Add a function to generate a list of prime numbers upto 'n' (parameter) as described in [Contribution.md](../blob/main/Contribution.md).
Give a small proposal describing your method of implementation.

Checklist:
- [ ] Added the files sieve.py, sieve.java and sieve.cpp in the corresponding directory
- [ ] My code aligns with the specified structure.
- [ ] Updated [RoadMap.md](../blob/main/RoadMap.md)

**Comment by Aditi-Anil-P** [comment]
I am interested in contributing to this issue.

**Comment by imsuraj675** [comment]
Have you filled the google form?

**Comment by Aditi-Anil-P** [comment]
> Have you filled the google form?
Yes [Aditi Anil Pulikottil , 2024ITB036]

**Comment by sayaksen18** [comment]
I am interested.

**Comment by imsuraj675** [comment]
@Aditi-Anil-P Go ahead
