### ISSUE TITLE
[ADD] Graph Algorithms: Dijkstra's Algorithm

### ISSUE THREAD

**Issue by Vaibhavv1703** [imsuraj675/CodeStock#40]
I'd like to work on this, please assign me

**Comment by imsuraj675** [comment]
@Vaibhavv1703 Go ahead. Make sure you follow standard coding practice to write the code for this algorithm. Also make sure that your code fails on negative edges (not runs infinitely)

**Comment by Vaibhavv1703** [comment]
Yes, I'll see to it

**Comment by Vaibhavv1703** [comment]
What should the function return in case of negative edges?

**Comment by imsuraj675** [comment]
It should work as expected. It should return the answer (as distance matrix) and of course it may contain wrong answers, as Dijkstra's Algorithm is not supposed to work correctly on it. The thing is it should not run indefinitely.

**Comment by Vaibhavv1703** [comment]
Alright, I'll do that
