### ISSUE TITLE
[ADD] Array Functions : Print 2D Matrix

### ISSUE THREAD

**Issue by Aditi-Anil-P** [imsuraj675/CodeStock#42]
I am interested in contributing to this issue. 

-Approach: Through nested loops traversing and printing each element of the array .
- Time Complexity : O(N^2)
- Space Complexity: O(1)

**Comment by imsuraj675** [comment]
@Aditi-Anil-P Go ahead. Just write a function with void return type, to print the contents to 2D array, in the form of matrix. You can take the 2d array as input
