### ISSUE TITLE
[ADD] Number Theory: Get All Factors (Map)

### ISSUE THREAD

**Issue by Aditi-Anil-P** [imsuraj675/CodeStock#48]
- To implement respective function in C++,Java and Python to get all factors of a number N.
- The above issue can be solved in O(N^(1/2)) time complexity and space complexity of  O(M) where M is the no of factors.

I am interested in contributing to the above issue.

**Comment by imsuraj675** [comment]
@Aditi-Anil-P Go ahead, just return an array containing all the factors,
