### ISSUE TITLE
[Add] Miscellaneous: Sparse Table (Min, Max, And, Or, Gcd, Lcm)

### ISSUE THREAD

**Issue by imsuraj675** [imsuraj675/CodeStock#5]
Add a class to create Sparse Table which can perform Min, Max, And, Or, Gcd, Lcm as per requirement on a range. The type of function will be passed as a string parameter to this class.
For reference check [Contribution.md](../blob/main/Contribution.md).
Give a small proposal describing your method of implementation.

Checklist:
- [ ] Added the files sparse.py, sparse.java and sparse.cpp in the corresponding directory
- [ ] My code aligns with the specified structure.
- [ ] Updated [RoadMap.md](../blob/main/RoadMap.md)

**Comment by flex0ing-ag** [comment]
I would like to work on this issue. Please assign me this issue.

**Comment by imsuraj675** [comment]
@flex0ing-ag Go ahead. Make sure to add the code in proper format, assuring all the possible edge cases. The function upon which the Sparse Table will be based on, will be a string parameter, and on that basis implement the class. You have to implement build (array, array_size, func_name) and query function (left, right).
