### ISSUE TITLE
[ADD] Number Theory : LCM of 'a' and 'b'

### ISSUE THREAD

**Issue by riddhi-a23** [imsuraj675/CodeStock#53]
To find the LCM of 'a' and 'b', I'll first find GCD and then apply the formula LCM = (a*b)/GCD.

I'd like to contribute to the above mentioned issue.

**Comment by imsuraj675** [comment]
@riddhi-a23 Go ahead. For GCD, you can pick code from already implemented GCD code in this repository. Make sure to make any necessary changes if nedded
