### ISSUE TITLE
[ADD] Graph Functions: Prim's Algorithm

### ISSUE THREAD

**Issue by Vaibhavv1703** [imsuraj675/CodeStock#58]
I'd like to work on this issue, please assign it to me.

**Comment by imsuraj675** [comment]
@Vaibhavv1703 Go ahead. Make sure to implement the algorithm in the correct way. Implement the algorithm in two ways, one is ElogV for sparse graphs and another for dense graph in V^2.

**Comment by Vaibhavv1703** [comment]
Okay, I'll do that
