### ISSUE TITLE
[Add] Array functions Binary Search

### ISSUE THREAD

**Issue by Mayank9207** [imsuraj675/CodeStock#8]
It is an highly efficient algorithm to search a sorted space

**Comment by ittou-shura** [comment]
I am interested in Contributing to this issue

**Comment by imsuraj675** [comment]
@Mayank9207 and @ittou-shura Complete the assigned work first

**Comment by AShaw110** [comment]
I have understood the contribution guidelines and want to work on this issue.

**Comment by sayaksen18** [comment]
I am interested.

**Comment by abhra2911** [comment]
I would like to work on this issue.

**Comment by imsuraj675** [comment]
@AShaw110 Go ahead
